### ISSUE TITLE
[POSTIFY] Criação da interface de criação do post

### ISSUE THREAD

**Issue by miasK3011** [es20232/eqp3#19]
Tela para realizar a criação de um post

**Comment by miasK3011** [comment]
A interface da página de post está assim: 



![Image](https://github.com/es20232/eqp3/assets/70519524/950157de-1736-4251-b34e-6adcea2d47f3)

**Comment by FranCosMonX** [comment]
para adicionar uma imagem tem que clicar em qualquer lugar desta área onde a imagem ficará?
